code cleanup

diff --git a/modules/do-exit b/modules/do-exit
--- a/modules/do-exit
+++ b/modules/do-exit
@@ -1,58 +1,58 @@
 #!/bin/bash
 
 # start with 80 to 113 to be compliant with c
-if  [ "${exit_code}" == "0" ]
-	then	:
-	elif [ "${exit_code}" == "80" ]
-		then	echo "${module_current}: The VM ${current_sync_vmid} does not exist" && exit 1
+if  [[ "${exit_code}" == "0" ]]; then
+	:;
+elif [[ "${exit_code}" == "80" ]]; then
+	echo "${module_current}: The VM ${current_sync_vmid} does not exist" && exit 1;
 
-	elif [ "${exit_code}" == "81" ]
-		then	echo "${current_path_root}${current_path_offset}/${current_sync_name_source} does not exist" && exit 1
+elif [[ "${exit_code}" == "81" ]]; then
+	echo "${current_path_root}${current_path_offset}/${current_sync_name_source} does not exist" && exit 1;
 
-	elif [ "${exit_code}" == "82" ]
-		then	echo "${module_current}: btrfs send does not work if the source ${current_path_root}/${current_sync_name} does not exist or is no subvolume" && exit 1
+elif [[ "${exit_code}" == "82" ]]; then
+	echo "${module_current}: btrfs send does not work if the source ${current_path_root}/${current_sync_name} does not exist or is no subvolume" && exit 1;
 
-	elif [ "${exit_code}" == "83" ]
-		then	echo "${module_current}: btrfs should be used for snapshots but neither ${current_path_root} nor ${current_path_root}/${current_sync_name} is a btrfs subvolume" && exit 1
+elif [[ "${exit_code}" == "83" ]]; then
+	echo "${module_current}: btrfs should be used for snapshots but neither ${current_path_root} nor ${current_path_root}/${current_sync_name} is a btrfs subvolume" && exit 1;
 
-	elif [ "${exit_code}" == "84" ]
-		then	echo "${module_current}: no subvolume has been found under snapshot-path ${current_snap_set}" && exit 1
+elif [[ "${exit_code}" == "84" ]]; then
+	echo "${module_current}: no subvolume has been found under snapshot-path ${current_snap_set}" && exit 1;
 
-	elif [ "${exit_code}" == "85" ]
-		then	echo "${module_current}: zfs send does not work if the source ${current_path_snap}/${current_sync_name} does not exist" && exit 1
+elif [[ "${exit_code}" == "85" ]]; then
+	echo "${module_current}: zfs send does not work if the source ${current_path_snap}/${current_sync_name} does not exist" && exit 1;
 
-	elif [ "${exit_code}" == "86" ]
-		then	echo "${module_current}: zfs should be used for snapshots but neither ${current_path_snap} nor ${current_path_snap}/${current_sync_name} is a zfs dataset" && exit 1
+elif [[ "${exit_code}" == "86" ]]; then
+	echo "${module_current}: zfs should be used for snapshots but neither ${current_path_snap} nor ${current_path_snap}/${current_sync_name} is a zfs dataset" && exit 1;
 
-	elif [ "${exit_code}" == "87" ]
-		then	echo "${module_current}: current_snap_set does not exist" && exit 1
+elif [[ "${exit_code}" == "87" ]]; then
+	echo "${module_current}: current_snap_set does not exist" && exit 1;
 
-	elif [ "${exit_code}" == "88" ]
-		then	echo "${module_current}: For source are no snapshots available" && exit 1
+elif [[ "${exit_code}" == "88" ]]; then
+	echo "${module_current}: For source are no snapshots available" && exit 1;
 
-	elif [ "${exit_code}" == "89" ]
-		then	echo "${module_current}: no common snapshot on source and target was found" && exit 1
+elif [[ "${exit_code}" == "89" ]]; then
+	echo "${module_current}: no common snapshot on source and target was found" && exit 1;
 
-	elif [ "${exit_code}" == "90" ]
-		then	echo "${module_current}: mode_snapshot is file but snap_new_source does not exist" && exit 1
+elif [[ "${exit_code}" == "90" ]]; then
+	echo "${module_current}: mode_snapshot is file but snap_new_source does not exist" && exit 1;
 
-	elif [ "${exit_code}" == "91" ]
-		then	echo "${module_current}: The credential-file ${elem_options_sql} does not exist" && exit 1
+elif [[ "${exit_code}" == "91" ]]; then
+	echo "${module_current}: The credential-file ${elem_options_sql} does not exist" && exit 1;
 
-	elif [ "${exit_code}" == "92" ]
-		then	echo "${module_current}: a certificate is set: ${elem_certificate} but it does not exist" && exit 1
+elif [[ "${exit_code}" == "92" ]]; then
+	echo "${module_current}: a certificate is set: ${elem_certificate} but it does not exist" && exit 1;
 
-	elif [ "${exit_code}" == "93" ]
-		then	echo "${module_current}: the database ${current_sync_name_source} does not exist" && exit 1
+elif [[ "${exit_code}" == "93" ]]; then
+	echo "${module_current}: the database ${current_sync_name_source} does not exist" && exit 1;
 
-	# 94 was: "set-multisnap: there are no snapshots to copy matching your pattern ${arg_snap_multi}"
+# 94 was: "set-multisnap: there are no snapshots to copy matching your pattern ${arg_snap_multi}"
 
-	# prepared but not used at the moment because check-config and the main script are in the same shell
-	elif [ "${exit_code}" == "95" ]
-		then	echo "${module_current}: no supported output found: ${arg_output}" && exit 1
+# prepared but not used at the moment because check-config and the main script are in the same shell
+elif [ "${exit_code}" == "95" ]]; then
+	echo "${module_current}: no supported output found: ${arg_output}" && exit 1;
 
-	elif [ "${exit_code}" == "96" ]
-		then	echo "${module_current}: root-set ${current_path_root}${current_path_offset}/${current_sync_name_source} does not exist" && exit 1
+elif [ "${exit_code}" == "96" ]]; then
+	echo "${module_current}: root-set ${current_path_root}${current_path_offset}/${current_sync_name_source} does not exist" && exit 1; else
 
-	else	echo "${module_current}: an undefined error has occured: ${?}" && exit 1
+	echo "${module_current}: an undefined error has occured: ${?}" && exit 1
 fi
diff --git a/modules/set-snapvars b/modules/set-snapvars
--- a/modules/set-snapvars
+++ b/modules/set-snapvars
@@ -5,86 +5,86 @@
 # snap_common_source - this is the last common snapshot on source and target. It is needed for btrfs and zfs send and file for copying multiple snapshots
 # snap_old_target - this is always the newest snapshot on target. It is needed for zfs rollback and log
 
-if [ "${mode_transfer}" == "zfs" ] || [ "${mode_transfer}" == "btrfs" ] || ([ "${mode_transfer}" == "rsync" ] && [ -n "${arg_snap_multi}" ])
-	then	# if mode_transfer is either zfs or btrfs snapshots on source have to exist
-		if [ ! -n "${current_snap_shots_source}" ]
-			then	exit 88
-		fi
+if [[ "${mode_transfer}" == "zfs" ]] || [[ "${mode_transfer}" == "btrfs" ]] || ([[ "${mode_transfer}" == "rsync" ]] && [[ -n "${arg_snap_multi}" ]]); then
+	# if mode_transfer is either zfs or btrfs snapshots on source have to exist
+	if [[ ! -n "${current_snap_shots_source}" ]]; then
+		exit 88
+	fi
 
-		# if snapshots on source are <2 or on target <1 the loop would fail
-		if [  "${current_snap_number_target}" -lt 1 ] || [ "${current_snap_number_source}" -lt 2 ]
-			then	snap_common_source=unset
-		fi
+	# if snapshots on source are <2 or on target <1 the loop would fail
+	if [[  "${current_snap_number_target}" -lt 1 ]] || [[ "${current_snap_number_source}" -lt 2 ]]; then
+		snap_common_source=unset
+	fi; else
 
-		# if mode_snapshot is zfs/btrfs and mode_transfer differs a snap_common_source wouldn't necessarily exist
-	else	snap_common_source=unset
+	# if mode_snapshot is zfs/btrfs and mode_transfer differs a snap_common_source wouldn't necessarily exist
+	snap_common_source=unset
 fi
 
 # if snap_common_source isn't set to unset it is determined here
-if [ ! "${snap_common_source}" == "unset" ]
-	then	# the snapshots can contain spaces. since the strings are counted the spaces have to be replaced
-		IFSBAK=$IFS
-		IFS=$'\n'
-		snap_shots_source=(${current_snap_shots_source})
-		snap_shots_target=(${current_snap_shots_target})
-		snap_shots_source_ts=(${current_snap_shots_source_ts})
-		IFS=$IFSBAK
-		bb=$((${current_snap_number_source} - 1))
+if [[ ! "${snap_common_source}" == "unset" ]]; then
+	# the snapshots can contain spaces. since the strings are counted the spaces have to be replaced
+	IFSBAK=$IFS
+	IFS=$'\n'
+	snap_shots_source=(${current_snap_shots_source})
+	snap_shots_target=(${current_snap_shots_target})
+	snap_shots_source_ts=(${current_snap_shots_source_ts})
+	IFS=$IFSBAK
+	bb=$((${current_snap_number_source} - 1))
 
-		while [ "${bb}" -ge 0 ]
-		do	# for zfs timestamps on source and target are the same
-			# for now timestamps are not applicable for btrfs, since there is now way to preserve the actual creation time of a snapshot
-			# a relationship between source and target snapshots could be established with the received uuid, but this wouldn't work
-			# if another fs like a cold backup is used or if the snapshot on source is snapshotted
-			# the current workaround is to ignore the timestamp and use the newest snapshot with the same name
-			if [ "${mode_transfer}" == "zfs" ]
-				then	timestamps_matching=$(echo "${current_snap_shots_target_ts}" | grep -n "${snap_shots_source_ts[${bb}]}" | grep -Eo '^[^:]+')
-				elif [ "${mode_transfer}" == "btrfs" ] || [ "${mode_transfer}" == "rsync" ]
-					then	timestamps_matching=set
-			fi
-			# snap_common_source is determined through matching timestamp and matching snapstring
-			if [ -n "${timestamps_matching}" ]
-				then	# get snapstring for source. for zfs source and target can differ in snapname, for btrfs and file it is the same
-					if [ "${mode_transfer}" == "zfs" ]
-						then	snap_string_source=$(echo "${snap_shots_source[${bb}]}" | rev | cut -d "@" -f 1 | rev)
-						else 	snap_string_source=$(echo "${snap_shots_source[${bb}]}" | rev | cut -d "/" -f 1 | rev)
-					fi
-					# there could be multiple timestamps with the same value
-					for timestamp_matching in ${timestamps_matching}
-					do	timestamp_matching=$((${timestamp_matching} - 1))
-						if [ "${mode_transfer}" == "zfs" ]
-							then	snap_string_target=$(echo "${snap_shots_target[${timestamp_matching}]}" | rev | cut -d "@" -f 1 | rev)
-							else 	snap_string_target=$(echo "${snap_shots_target[${timestamp_matching}]}" | rev | cut -d "/" -f 1 | rev)
-						fi
-
-						if [ "${snap_string_source}" == "${snap_string_target}" ]
-							then	snap_common_source=${snap_shots_source[${bb}]}
-								break
-						fi
-					done
-			fi
-
-			if [ -n "${snap_common_source}" ]
-				then	break
-				else	bb=$((${bb} - 1))
-			fi
-		done
-
-		if [ "${current_snap_number_source}" -eq "$((${bb} + 1))" ]
-			then	# if this is true the common snapshot is the newest on source and send would fail
-				snap_common_source=newest
+	while [[ "${bb}" -ge 0 ]]
+	do	# for zfs timestamps on source and target are the same
+		# for now timestamps are not applicable for btrfs, since there is now way to preserve the actual creation time of a snapshot
+		# a relationship between source and target snapshots could be established with the received uuid, but this wouldn't work
+		# if another fs like a cold backup is used or if the snapshot on source is snapshotted
+		# the current workaround is to ignore the timestamp and use the newest snapshot with the same name
+		if [[ "${mode_transfer}" == "zfs" ]]; then
+			timestamps_matching=$(echo "${current_snap_shots_target_ts}" | grep -n "${snap_shots_source_ts[${bb}]}" | grep -Eo '^[^:]+');
+		elif [[ "${mode_transfer}" == "btrfs" ]] || [[ "${mode_transfer}" == "rsync" ]]; then
+			timestamps_matching=set
 		fi
+		# snap_common_source is determined through matching timestamp and matching snapstring
+		if [[ -n "${timestamps_matching}" ]]; then
+			# get snapstring for source. for zfs source and target can differ in snapname, for btrfs and file it is the same
+			if [[ "${mode_transfer}" == "zfs" ]]; then
+				snap_string_source=$(echo "${snap_shots_source[${bb}]}" | rev | cut -d "@" -f 1 | rev); else
+				snap_string_source=$(echo "${snap_shots_source[${bb}]}" | rev | cut -d "/" -f 1 | rev)
+			fi
+			# there could be multiple timestamps with the same value
+			for timestamp_matching in ${timestamps_matching}
+			do	timestamp_matching=$((${timestamp_matching} - 1))
+				if [[ "${mode_transfer}" == "zfs" ]]; then
+					snap_string_target=$(echo "${snap_shots_target[${timestamp_matching}]}" | rev | cut -d "@" -f 1 | rev); else
+					snap_string_target=$(echo "${snap_shots_target[${timestamp_matching}]}" | rev | cut -d "/" -f 1 | rev)
+				fi
+
+				if [[ "${snap_string_source}" == "${snap_string_target}" ]]; then
+					snap_common_source=${snap_shots_source[${bb}]}
+					break
+				fi
+			done
+		fi
+
+		if [[ -n "${snap_common_source}" ]]; then
+			break; else
+			bb=$((${bb} - 1))
+		fi
+	done
+
+	if [[ "${current_snap_number_source}" -eq "$((${bb} + 1))" ]]; then
+		# if this is true the common snapshot is the newest on source and send would fail
+		snap_common_source=newest
+	fi
 fi
 
 # if at this point snap_common_source does not exist, there is no common snapshot and source and target
-if [ ! -n "${snap_common_source}" ]
-	then	exit 89
+if [[ ! -n "${snap_common_source}" ]]; then
+	exit 89
 fi
 
 # if no snapshots on target exist, snap_old_target hast to be unset
-if [ -n "${current_snap_shots_target}" ]
-	then	snap_old_target=${current_snap_shots_target##*$'\n'}
-	else	snap_old_target=unset
+if [[ -n "${current_snap_shots_target}" ]]; then
+	snap_old_target=${current_snap_shots_target##*$'\n'}; else
+	snap_old_target=unset
 fi
 
 echo "${snap_common_source}~${snap_old_target}"
