debug can create dumps of all modules

diff --git a/modules/do-exit b/modules/do-exit
--- a/modules/do-exit
+++ b/modules/do-exit
@@ -1,57 +1,59 @@
 #!/bin/bash
 
 # start with 80 to 113 to be compliant with c
-if [ "${exit_code}" == "80" ]
-	then	echo "check-create: The VM ${sync_vmid_current} does not exist" && exit 1
+if  [ "${exit_code}" == "0" ]
+	then	:
+	elif [ "${exit_code}" == "80" ]
+		then	echo "${module_current}: The VM ${sync_vmid_current} does not exist" && exit 1
 
 	elif [ "${exit_code}" == "81" ]
-		then	echo "check-copy: ${dir_root_current}${dir_offset_current}/${sync_name_current} does not exist" && exit 1
+		then	echo "${dir_root_current}${dir_offset_current}/${sync_name_current} does not exist" && exit 1
 
 	elif [ "${exit_code}" == "82" ]
-		then	echo "check-btrfs: btrfs send does not work if the source ${dir_root_current}/${sync_name_current} does not exist or is no subvolume" && exit 1
+		then	echo "${module_current}: btrfs send does not work if the source ${dir_root_current}/${sync_name_current} does not exist or is no subvolume" && exit 1
 
 	elif [ "${exit_code}" == "83" ]
-		then	echo "check-btrfs: btrfs should be used for snapshots but neither ${dir_root_current} nor ${dir_root_current}/${sync_name_current} is a btrfs subvolume" && exit 1
+		then	echo "${module_current}: btrfs should be used for snapshots but neither ${dir_root_current} nor ${dir_root_current}/${sync_name_current} is a btrfs subvolume" && exit 1
 
 	elif [ "${exit_code}" == "84" ]
-		then	echo "check-btrfs: no subvolume has been found under snapshot-directory ${snap_set_current}" && exit 1
+		then	echo "${module_current}: no subvolume has been found under snapshot-directory ${snap_set_current}" && exit 1
 
 	elif [ "${exit_code}" == "85" ]
-		then	echo "check-zfs: zfs send does not work if the source ${dir_snap_current}/${sync_name_current} does not exist" && exit 1
+		then	echo "${module_current}: zfs send does not work if the source ${dir_snap_current}/${sync_name_current} does not exist" && exit 1
 
 	elif [ "${exit_code}" == "86" ]
-		then	echo "check-zfs: zfs should be used for snapshots but neither ${dir_snap_current} nor ${dir_snap_current}/${sync_name_current} is a zfs dataset" && exit 1
+		then	echo "${module_current}: zfs should be used for snapshots but neither ${dir_snap_current} nor ${dir_snap_current}/${sync_name_current} is a zfs dataset" && exit 1
 
 	elif [ "${exit_code}" == "87" ]
-		then	echo "check-file: snap_set_current does not exist" && exit 1
+		then	echo "${module_current}: snap_set_current does not exist" && exit 1
 
 	elif [ "${exit_code}" == "88" ]
-		then	echo "set-snapvars: For source are no snapshots available" && exit 1
+		then	echo "${module_current}: For source are no snapshots available" && exit 1
 
 	elif [ "${exit_code}" == "89" ]
-		then	echo "set-snapvars: no common snapshot on source and target was found" && exit 1
+		then	echo "${module_current}: no common snapshot on source and target was found" && exit 1
 
 	elif [ "${exit_code}" == "90" ]
-		then	echo "get-synclist: spaces are not allowed in filenames for btrfs subvolumes" && exit 1
+		then	echo "${module_current}: spaces are not allowed in filenames for btrfs subvolumes" && exit 1
 
 	elif [ "${exit_code}" == "91" ]
-		then	echo "check-create: The credential-file ${config_sql_credentials} does not exist" && exit 1
+		then	echo "${module_current}: The credential-file ${config_sql_credentials} does not exist" && exit 1
 
 	elif [ "${exit_code}" == "92" ]
-		then	echo "check-create: a certificate is set: ${config_sql_certificate} but it does not exist" && exit 1
+		then	echo "${module_current}: a certificate is set: ${config_sql_certificate} but it does not exist" && exit 1
 
 	elif [ "${exit_code}" == "93" ]
-		then	echo "check-create: the database ${sync_name_source_current} does not exist" && exit 1
+		then	echo "${module_current}: the database ${sync_name_source_current} does not exist" && exit 1
 
 	elif [ "${exit_code}" == "94" ]
-		then	echo "set-multisnap: there are no snapshots to copy matching your pattern ${snap_multi}" && exit 1
+		then	echo "${module_current}: there are no snapshots to copy matching your pattern ${snap_multi}" && exit 1
 
 	# prepared but not used at the moment because check-config and the main script are in the same shell
 	elif [ "${exit_code}" == "95" ]
-		then	echo "no supported debug-level found: ${output}" && exit 1
+		then	echo "${module_current}: no supported output found: ${output}" && exit 1
 
 	elif [ "${exit_code}" == "96" ]
-		then	echo "check-file: root-set ${dir_root_current} or ${dir_root_current}${dir_offset_current}/${sync_name_source_current} does not exist" && exit 1
+		then	echo "${module_current}: root-set ${dir_root_current} or ${dir_root_current}${dir_offset_current}/${sync_name_source_current} does not exist" && exit 1
 
-	else	echo "an undefined error has occured: ${?}" && exit 1
+	else	echo "${module_current}: an undefined error has occured: ${?}" && exit 1
 fi
