remove necessity for snap_common_source in case mode_transfer is not mode_snapshot

diff --git a/modules/set-snapvars b/modules/set-snapvars
--- a/modules/set-snapvars
+++ b/modules/set-snapvars
@@ -3,17 +3,25 @@
 # 3 Snapshots are needed:
 # snap_new_source - this is always the newest snapshot
 # snap_common_source - this is the last common snapshot on source and target
-# snap_old_target - this is the newest snapshot on target. It is only needed with zfs for rollback
+# snap_old_target - this is always the newest snapshot on target. It is only needed with zfs for rollback
 
-if [ "${mode_snapshot}" == "zfs" ] || [ "${mode_snapshot}" == "btrfs" ]
-	then	# Check if sourcesnaps exist. Without it all zfs and btrfs send will fail
+if [ "${mode_transfer}" == "zfs" ] || [ "${mode_transfer}" == "btrfs" ]
+	then	# if mode_transfer is either zfs or btrfs snapshots on source have to exist
 		if [ ! -n "${snap_shots_source_current}" ]
 			then	exit 88
 		fi
+
+		# if snapshots on source are <2 or on target <1 the loop would fail
+		if [ ! "${snap_number_target_current}" -ge 1 ] && [ ! "${snap_number_source_current}" -ge 2 ]
+			then	snap_common_source=unset
+		fi
+
+		# if mode_snapshot is zfs/btrfs and mode_transfer differs a snap_common_source wouldn't necessarily exist
+	else	snap_common_source=unset
 fi
 
-# if snapshots exist on target the newest common snapshot between source and target, snap_common_source, needs to be be determined
-if [ "${snap_number_target_current}" -ge 1 ] && [ "${snap_number_source_current}" -ge 2 ]
+# if snap_common_source isn't set to unset it is determined here
+if [ ! "${snap_common_source}" == "unset" ]
 	then	probe_snap_shots_source=${snap_shots_source_current}
 		bb=${snap_number_source_current}
 
@@ -34,18 +42,13 @@ if [ "${snap_number_target_current}" -ge 1 ] && [ "${snap_number_source_current}
 		if [ "${snap_number_source_current}" -eq "${bb}" ]
 			then	# if this is true the common snapshot is the newest on source and send would fail
 				snap_common_source=newest
-			else	snapvars_loops=passed
 		fi
 fi
 
 # if no snaphots on target are found snap_common_source is "unset". If no common snapshot is found the script exits with an error
 if [ ! -n "${snap_common_source}" ]
-	then	if [ "${snapvars_loops}" == "passed" ]
-			then	exit 89
-			else	snap_common_source=unset
-				snap_old_target=unset
-		fi
-	else	snap_old_target=$(echo ${snap_shots_target_current} | awk '{print $(NF)}')
+	then	exit 89
 fi
 
+snap_old_target=$(echo ${snap_shots_target_current} | awk '{print $(NF)}')
 echo "${snap_common_source} ${snap_old_target} ${bb}"
